version: '3.9'
services:
  drone_jenkins:
    image: ilhamfadhilah/drone-jenkins-deployment:local
    build:
      context: .
      dockerfile: dockerfile
    environment:
      - PLUGIN_JENKINS_HOST
      - PLUGIN_JENKINS_JOB
      - PLUGIN_STAGE
      - PLUGIN_SERVICE_NAME
      - PLUGIN_AUTH_USERNAME
      - PLUGIN_AUTH_TOKEN
